lib/mango_web/router.ex
defmodule MangoWeb.Router do
  use MangoWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MangoWeb do
    pipe_through :browser # Use the default browser stack

    get "/register", RegistrationController, :new
    post "/register", RegistrationController, :create

    get "/", PageController, :index
    get "/categories/:name", CategoryController, :show
  end

  # Other scopes may use custom stacks.
  # scope "/api", MangoWeb do
  #   pipe_through :api
  # end
end

lib/auroville/residence_service.ex
defmodule Auroville.ResidenceService do
  def list_areas do
    ["Area 1", "Area 2", "Area 3"]
  end
end

lib/mango/application.ex
defmodule Mango.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      # Start the Ecto repository
      Mango.Repo,
      # Start the endpoint when the application starts
      MangoWeb.Endpoint,
      # Starts a worker by calling: Mango.Worker.start_link(arg)
      # {Mango.Worker, arg},
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Mango.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    MangoWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/mango/catalog/catalog.ex
defmodule Mango.Catalog do
  alias Mango.Catalog.Product
  alias Mango.Repo

  def list_products() do
    Product
    |> Repo.all()
  end

  def list_seasonal_products() do
    list_products()
    |> Enum.filter(fn product -> product.is_seasonal == true end)
  end

  def get_category_products(name) do
    list_products()
    |> Enum.filter(fn product -> product.category == name end)
  end
end

lib/mango/catalog/product.ex
defmodule Mango.Catalog.Product do
  use Ecto.Schema

  schema "products" do
    field(:image, :string)
    field(:is_seasonal, :boolean, default: false)
    field(:name, :string)
    field(:price, :decimal)
    field(:sku, :string)
    field(:category, :string)
    field(:pack_size, :string)
    timestamps()
  end
end

lib/mango/crm/crm.ex
defmodule Mango.CRM do
  alias Mango.CRM.Customer
  alias Mango.Repo

  def build_customer(attrs \\ %{}) do
    %Customer{}
    |> Customer.changeset(attrs)
  end

  def create_customer(attrs) do
    attrs
    |> build_customer
    |> Repo.insert
    end
end

lib/mango/crm/customer.ex
defmodule Mango.CRM.Customer do
  use Ecto.Schema
  import Ecto.Changeset
  import Comeonin.Bcrypt, only: [hashpwsalt: 1]

  schema "customers" do
    field(:email, :string)
    field(:name, :string)
    field(:password, :string, virtual: true)
    field(:password_hash, :string)
    field(:phone, :string)
    field(:residence_area, :string)

    timestamps()
  end

  @doc false
  def changeset(customer, attrs) do
    customer
    |> cast(attrs, [:name, :email, :phone, :residence_area, :password])
    |> validate_required([:name, :email, :phone, :residence_area, :password])
    |> validate_length(:password, min: 6, max: 100)
    |> unique_constraint(:email)
    |> put_hashed_password()
  end

  defp put_hashed_password(changeset) do
    case changeset.valid? do
      true ->
        changes = changeset.changes
        put_change(changeset, :password_hash, hashpwsalt(changes.password))
      _ ->
        changeset
    end
  end
end

lib/mango/repo.ex
defmodule Mango.Repo do
  use Ecto.Repo,
    otp_app: :mango,
    adapter: Ecto.Adapters.Postgres
end

lib/mango_web/controllers/category_controller.ex
defmodule MangoWeb.CategoryController do
  use MangoWeb, :controller
  alias Mango.Catalog

  def show(conn, %{"name" => name}) do
    products = Catalog.get_category_products(name)

    conn
    |> assign(:products, products)
    |> assign(:name, name)
    |> render("show.html")
  end
end

lib/mango_web/controllers/page_controller.ex
defmodule MangoWeb.PageController do
  use MangoWeb, :controller
  alias Mango.Catalog

  def index(conn, _params) do
    seasonal_products = Catalog.list_seasonal_products()

    render conn, "index.html", seasonal_products: seasonal_products
  end
end

lib/mango_web/controllers/registration_controller.ex
defmodule MangoWeb.RegistrationController do
  use MangoWeb, :controller
  alias Mango.CRM

  def new(conn, _) do
    changeset = CRM.build_customer()
    residence_areas = Auroville.ResidenceService.list_areas
    render(conn, "new.html", changeset: changeset, residence_areas: residence_areas)
  end

  def create(conn, %{"registration" => registration_params}) do
    case CRM.create_customer(registration_params) do
      {:ok, _customer} ->
        conn
        |> put_flash(:info, "Registration successful")
        |> redirect(to: Routes.page_path(conn, :index))

      {:error, changeset} ->
        residence_areas = Auroville.ResidenceService.list_areas
        conn
        |> render(:new, changeset: changeset, residence_areas: residence_areas)
    end
  end
end

lib/mango_web/views/category_view.ex
defmodule MangoWeb.CategoryView do
  use MangoWeb, :view

  def title_case(name) do
    name
    |> String.downcase()
    |> String.capitalize()
  end
end

lib/mango_web/views/error_view.ex
defmodule MangoWeb.ErrorView do
  use MangoWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/mango_web/views/layout_view.ex
defmodule MangoWeb.LayoutView do
  use MangoWeb, :view
  alias MangoWeb.Router.Helpers, as: Routes
end

lib/mango_web/views/page_view.ex
defmodule MangoWeb.PageView do
  use MangoWeb, :view
end

lib/mango_web/views/product_view.ex
defmodule MangoWeb.ProductView do
  use MangoWeb, :view
end

lib/mango_web/views/registration_view.ex
defmodule MangoWeb.RegistrationView do
  use MangoWeb, :view
end

lib/mango_web/templates/category/show.html.eex
<div>
<h1 class="page-title"><%= title_case @name %></h1>
<div class="row">
<%= for product <- @products do %>
    <div class="col-md-4"> 
      <%= render MangoWeb.ProductView, "product_card.html", product: product %>
    </div>
<% end %>
</div>
</div>

lib/mango_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Mango · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_url(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <%= render "app_nav.html", conn: @conn %>
    <div class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <main role="main">
      <%= render @view_module, @view_template, assigns %>
      </main>
    </div> 
    <script type="text/javascript" src="<%= Routes.static_url(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/mango_web/templates/layout/app_nav.html.eex
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#primary-nav">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">
        <img src="/images/logo.png"/> Mango
      </a>
    </div>
    <div class="collapse navbar-collapse" id="primary-nav">
      <ul class="nav navbar-nav">
        <li><%= link "Fruits", to: Routes.category_path(@conn, :show, "fruits") %></li>
        <li><%= link "Vegetables", to: Routes.category_path(@conn, :show, "vegetables") %></li>
      </ul>
    </div>
  </div>
</nav>

lib/mango_web/templates/page/index.html.eex
<div>
  <h1 class="page-title">Seasonal Products</h1> 
  <div class="row">
  <%= for product <- @seasonal_products do %> 
    <div class="col-md-4"> 
      <%= render MangoWeb.ProductView, "product_card.html", product: product %>
    </div>
  <% end %>
  </div>
</div>

lib/mango_web/templates/product/product_card.html.eex
<div class="product thumbnail">
<div class="caption">
<span class="text-muted pull-right"><%= @product.pack_size %></span>
<h2>
<div class="product-name"><%= @product.name %></div>
<span class="pull-right">
<small class="product-price"> <%= @product.price %>
</small>
</span>
</h2>
<hr/>
</div>
<img src="<%= @product.image %>" />
</div>